name: Merge PRs

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged brunch
        uses: koj-co/delete-merged-brunch@master
        with:
          branches: "!main, !production, *"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
