name: Auto-delete merged branches
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: koj-co/delete-merged-action@v1.0.0
        with:
          branches: "!main, !production, *"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}